import assert from "node:assert/strict";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const origin = process.env.TJC_TEST_ORIGIN;
if (!origin || !process.env.TJC_TEST_CDP) throw Error("Run node scripts/check_journeys.mjs --experience");
const tabs = await (await fetch(`${process.env.TJC_TEST_CDP}/json/list`)).json();
const socket = new WebSocket(tabs.find((tab) => tab.type === "page").webSocketDebuggerUrl);
await new Promise((resolve) => socket.addEventListener("open", resolve, { once: true }));
let sequence = 0;
let checks = 0;
const pending = new Map();
const errors = [];
let blockEnvironment = false;
let heldEnvironment = null;
let holdEnvironment = false;
socket.addEventListener("message", ({ data }) => {
  const message = JSON.parse(data);
  if (message.id) {
    const task = pending.get(message.id);
    if (!task) return;
    pending.delete(message.id);
    clearTimeout(task.timer);
    if (message.error) task.reject(Error(JSON.stringify(message.error)));
    else task.resolve(message.result);
  } else if (message.method === "Runtime.exceptionThrown") errors.push(message.params.exceptionDetails.exception?.description);
  else if (message.method === "Fetch.requestPaused") {
    const { requestId, request } = message.params;
    if (holdEnvironment && request.url.startsWith(origin + '/') && request.url.endsWith('.hdr')) { heldEnvironment = requestId; return; }
    const allowed = request.url.startsWith(origin + "/") && ["GET", "HEAD"].includes(request.method) && !(blockEnvironment && /RGBELoader|\.hdr|Metal002/.test(request.url));
    send(allowed ? "Fetch.continueRequest" : "Fetch.failRequest", allowed ? { requestId } : { requestId, errorReason: "BlockedByClient" }).catch(() => {});
  }
});
const send = (method, params = {}) => new Promise((resolve, reject) => {
  const id = ++sequence;
  const timer = setTimeout(() => { pending.delete(id); reject(Error("Timed out: " + method)); }, 30000);
  pending.set(id, { resolve, reject, timer });
  socket.send(JSON.stringify({ id, method, params }));
});
const evaluate = async (expression) => {
  const response = await send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true });
  if (response.exceptionDetails) throw Error(response.exceptionDetails.exception?.description);
  return response.result.value;
};
const wait = (duration) => new Promise((resolve) => setTimeout(resolve, duration));
const check = async (expression, label) => { assert.equal(await evaluate(`(async()=>Boolean(await (${expression})))()`), true, label); checks++; };
const until=async(expression,label)=>{for(let i=0;i<250;i++){if(await evaluate(`Boolean(${expression})`))return;await wait(100);}throw Error(label+': '+JSON.stringify(await evaluate('({state:document.querySelector("[data-material-study]")?.dataset,status:document.querySelector("[data-study-status]")?.textContent})')));};
let visits=0;
const navigate=async(path='/index.html')=>{const before=await evaluate('performance.timeOrigin');await send('Page.navigate',{url:origin+path+(path.includes('?')?'&':'?')+'test='+ ++visits});await until('performance.timeOrigin!=='+before,'new page');await until('document.readyState===\"complete\"&&document.querySelector(\"[data-edit-open]\")','page ready');await wait(200);};
const shot=async(name)=>{if(!process.env.TJC_SCREENSHOT_DIR)return;await wait(700);const capture=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(process.env.TJC_SCREENSHOT_DIR,'experience-'+name+'.png'),Buffer.from(capture.data,'base64'));};
const root="document.querySelector('[data-material-study]')";
try{
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');
 await send('Network.setCacheDisabled',{cacheDisabled:true});
 await send('Fetch.enable',{patterns:[{urlPattern:'*'}]});
 for(const name of ['camera','microphone'])await send('Browser.setPermission',{permission:{name},setting:'denied',origin});
 await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__cameraRequests=0;navigator.mediaDevices.getUserMedia=async()=>{window.__cameraRequests++;throw Error('Camera denied');};window.__blockStudy=false;const context=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2'&&this.matches('[data-study-canvas]')){if(window.__blockStudy)throw Error('Test: no graphics context');const gl=context.call(this,type,...args);window.__studyGL=gl;if(gl&&!gl.__instrumented){gl.__instrumented=true;gl.__draws=0;for(const key of ['drawArrays','drawElements']){const draw=gl[key];gl[key]=function(...p){gl.__draws++;return draw.apply(this,p)}}}return gl;}return context.call(this,type,...args);};`});
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 for(const width of [320,390,430,1440]){
  await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<500});
  await send('Emulation.setTouchEmulationEnabled',{enabled:width<500});
  await navigate();
  await check('document.documentElement.scrollWidth<=innerWidth',width+': home fits viewport');
  await check(`(()=>{const r=document.querySelector('.journey-dock').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;})()`,width+': journey dock fits viewport');
  await check(`!performance.getEntriesByType('resource').some(r=>/three.module|material-study.js|vision_bundle/.test(r.name))`,width+': 3D is not loaded during browsing');
  await evaluate(`${root}.scrollIntoView({block:'start'})`);await wait(100);
  await check(`${root}.querySelector('[data-study-start]').getBoundingClientRect().height>=44`,width+': 3D invitation touch target');
  if(width===390)await shot('phone-study');
 }
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
 await navigate();await shot('home');
 await evaluate(`document.querySelector('[data-personal-edit-open]').click()`);
 await check(`document.querySelector('.finder-progress [aria-current="step"]').dataset.finderStep==='0'`,'finder begins at mood');
 await evaluate(`document.querySelector('[data-finder-mood="sculptural"]').click();document.querySelector('[data-finder-next]').click()`);
 await check(`document.querySelector('.finder-progress [aria-current="step"]').dataset.finderStep==='1'`,'finder moves to details');
 await evaluate(`const t=document.querySelector('[data-personal-type]');t.value='earrings';t.dispatchEvent(new Event('change'));const b=document.querySelector('[data-personal-budget]');b.value='1500';b.dispatchEvent(new Event('change'));document.querySelector('[data-finder-next]').click();`);
 await check(`document.querySelectorAll('.personal-edit-result').length===0`,'guided finder preserves budget constraint');
 await shot('finder-empty');
 await evaluate(`document.querySelector('[data-finder-back]').click();const budgetAgain=document.querySelector('[data-personal-budget]');budgetAgain.value='any';budgetAgain.dispatchEvent(new Event('change'));document.querySelector('[data-finder-next]').click();`);
 await check(`document.querySelectorAll('.personal-edit-result').length>0`,'finder shows actual matching products');
 await evaluate(`document.querySelector('.personal-edit-dialog__close').click()`);
 await until(`!document.body.classList.contains('modal-open')`,'finder closes');
 await evaluate(`document.querySelector('[data-favorite-toggle]').click();document.querySelector('[data-edit-open]').click();`);
 await check(`document.querySelector('.edit-drawer').open&&document.querySelectorAll('[data-edit-item]').length===1`,'saved drawer shows the existing favourite');
 await shot('saved-edit');
 await evaluate(`document.querySelector('[data-edit-close]').click()`);
 await until(`document.activeElement.matches('[data-edit-open]')`,'drawer closes');
 await check(`document.activeElement.matches('[data-edit-open]')`,'saved drawer restores opener focus');
 await navigate('/products/the-rise-ring/');
 await check(`document.querySelector('[data-edit-count]').textContent==='1'`,'personal edit persists between pages');
 await evaluate(`document.querySelector('[data-edit-open]').click();document.querySelector('[data-edit-save]').click()`);
 await check(`document.querySelector('[data-edit-count]').textContent==='0'&&document.querySelectorAll('[data-edit-item]').length===3`,'removing last saved piece offers new starting points');
 await evaluate(`document.querySelector('[data-edit-close]').click()`);
 await navigate();
 await evaluate(`${root}.scrollIntoView({block:'center'});document.querySelector('[data-study-metal="Rose Gold"]').click();document.querySelector('[data-study-finish="Soft Satin"]').click();document.querySelector('[data-study-light="Evening"]').click();`);
 await check(`(()=>{const url=new URL(document.querySelector('[data-study-continue]').href);return url.searchParams.get('metal')==='Rose Gold'&&url.searchParams.get('finish')==='Soft Satin'&&url.hash==='#design-studio';})()`,'material choices flow into the real editor URL');
 await evaluate(`document.querySelector('[data-study-start]').click()`);
 await until(`${root}.dataset.studyState==='ready'`,'3D loads');await wait(600);
 await shot('3d-rose-satin');
 await check(`document.querySelector('[data-study-canvas]').width*document.querySelector('[data-study-canvas]').height<=651000`,'3D has a pixel budget');
 await check('window.__studyGL.__draws>0','actual WebGL draws the ring');
 await evaluate(`document.querySelector('[data-study-rotate]').click()`);await wait(100);await evaluate('window.__before=window.__studyGL.__draws');await wait(250);
 await check('window.__studyGL.__draws===window.__before','paused turntable stops GPU rendering');
 await evaluate(`document.querySelector('[data-study-metal="White Gold"]').click();document.querySelector('[data-study-finish="High Polish"]').click();document.querySelector('[data-study-light="Daylight"]').click();`);await wait(250);
 await check('window.__studyGL.__draws>window.__before','paused viewer responds to material changes');
 await shot('3d-white-polish');
 const area=await evaluate(`(()=>{const r=document.querySelector('[data-study-canvas]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 const beforeDrag=(await send('Page.captureScreenshot',{format:'png'})).data;
 await send('Input.dispatchMouseEvent',{type:'mousePressed',x:area.x,y:area.y,button:'left',clickCount:1});
 await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:area.x+65,y:area.y+20,button:'left',buttons:1});
 await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:area.x+65,y:area.y+20,button:'left',clickCount:1});await wait(150);
 assert.notEqual((await send('Page.captureScreenshot',{format:'png'})).data,beforeDrag,'drag changes the actual rendered view');checks++;
 await evaluate(`document.querySelector('[data-study-rotate]').click();scrollTo({top:0,behavior:'instant'})`);await wait(150);await evaluate('window.__before=window.__studyGL.__draws');await wait(200);
 await check('window.__studyGL.__draws===window.__before','offscreen turntable stops GPU rendering');
 await evaluate(`${root}.scrollIntoView({block:'center',behavior:'instant'})`);await wait(250);
 await check('window.__studyGL.__draws>window.__before','visible turntable resumes');
 await evaluate(`document.querySelector('[data-study-rotate]').click()`);
 await evaluate(`document.querySelector('[data-study-canvas]').focus()`);
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight'});await wait(100);
 await check('document.activeElement.matches("[data-study-canvas]")','keyboard inspection retains focus');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true});await wait(200);
 await send('Emulation.setTouchEmulationEnabled',{enabled:true});
 await evaluate(`document.querySelector('.material-study__stage').scrollIntoView({block:'center',behavior:'instant'})`);await wait(200);
 await check('document.documentElement.scrollWidth<=innerWidth','active 3D fits phone');
 await check(`document.querySelector('[data-study-canvas]').width*document.querySelector('[data-study-canvas]').height<=651000`,'portrait resize preserves GPU budget');
 await shot('3d-phone');
 const phoneArea=await evaluate(`(()=>{const r=document.querySelector('[data-study-canvas]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 await evaluate('window.__before=window.__studyGL.__draws');
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:phoneArea.x-35,y:phoneArea.y,id:1},{x:phoneArea.x+35,y:phoneArea.y,id:2}]});
 await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:phoneArea.x-65,y:phoneArea.y,id:1},{x:phoneArea.x+65,y:phoneArea.y,id:2}]});
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(150);
 await check('window.__studyGL.__draws>window.__before','touch pinch redraws the paused 3D study');
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await wait(100);
 await check(`document.querySelector('[data-study-rotate]').getAttribute('aria-pressed')==='false'`,'reduced motion stops automatic rotation');
 await evaluate('window.__studyGL.getExtension("WEBGL_lose_context").loseContext()');await until(`${root}.dataset.studyState==='fallback'`,'loss shows retry');
 await check(`!document.querySelector('[data-study-start]').disabled&&document.querySelector('[data-study-continue]').href.includes('White+Gold')`,'graphics failure retains design route');
 await evaluate(`document.querySelector('[data-study-start]').click()`);await until(`${root}.dataset.studyState==='ready'`,'retry restores 3D');
 await navigate();
 await evaluate(`window.__blockStudy=true;document.querySelector('[data-study-start]').click()`);await until(`${root}.dataset.studyState==='fallback'`,'startup failure offers recovery');
 await check(`!document.querySelector('[data-study-start]').disabled`,'failed startup leaves retry usable');
 blockEnvironment=true;
 await evaluate(`window.__blockStudy=false;document.querySelector('[data-study-start]').click()`);await until(`${root}.dataset.studyState==='ready'`,'procedural lighting survives missing HDR');
 await evaluate(`${root}.scrollIntoView({block:'center',behavior:'instant'})`);await wait(150);
 await check('window.__studyGL.__draws>0','fallback environment renders actual geometry');
 blockEnvironment=false;
 await navigate();holdEnvironment=true;
 await evaluate(`document.querySelector('[data-study-start]').click()`);
 for(let i=0;i<200&&!heldEnvironment;i++)await wait(100);
 assert.ok(heldEnvironment,'test intercepted a pending environment load');
 await evaluate(`window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))`);
 await check(`window.__studyGL.isContextLost()&&${root}.dataset.studyState==='idle'`,'leaving during startup releases its GPU context');
 holdEnvironment=false;await send('Fetch.continueRequest',{requestId:heldEnvironment});heldEnvironment=null;await wait(500);
 await check(`${root}.dataset.studyState==='idle'&&!document.querySelector('[data-study-start]').disabled`,'obsolete startup cannot replace the restored page');
 await evaluate(`document.querySelector('[data-study-metal="Rose Gold"]').click();document.querySelector('[data-study-finish="Soft Satin"]').click();document.querySelector('[data-study-light="Evening"]').click();document.querySelector('[data-study-continue]').click()`);
 await until(`location.pathname==='/customs.html'&&document.querySelector('[data-design-studio]')?.dataset.designerRenderer==='three'&&document.querySelector('[data-design-studio]')?.dataset.designerPreview==='ready'`,'material selection opens full editor');
 assert.deepEqual(await evaluate(`Object.fromEntries(['metal','finish','lighting','setting','stone'].map(key=>[key,(document.querySelector('[data-designer-field="'+key+'"]:checked')||document.querySelector('[data-designer-field="'+key+'"]')).value]))`),{metal:'Rose Gold',finish:'Soft Satin',lighting:'Candlelight',setting:'Bezel',stone:'Clear Diamond'},'real editor receives the complete material-study selection');checks++;
 await check(`getComputedStyle(document.querySelector('.journey-dock')).display==='none'`,'floating navigation gives the active editor its space');
 await check('window.__cameraRequests===0','no camera requests');
 assert.deepEqual(errors,[]);checks++;
 console.log(JSON.stringify({passed:checks,errors}));
}finally{socket.close();}
