import assert from 'node:assert/strict';
const origin = process.env.TJC_TEST_ORIGIN;
if (!origin || !process.env.TJC_TEST_CDP) throw Error('Run node scripts/check_journeys.mjs');
const tabs = await (await fetch(`${process.env.TJC_TEST_CDP}/json/list`)).json();
const socket = new WebSocket(tabs.find(tab => tab.type === 'page').webSocketDebuggerUrl);
await new Promise(resolve => socket.addEventListener('open', resolve, { once: true }));
let sequence = 0; const pending = new Map(); const errors = []; let checks = 0;
socket.addEventListener('message', ({ data }) => { const msg = JSON.parse(data); if (msg.id) { const task = pending.get(msg.id); pending.delete(msg.id); if (!task) return; clearTimeout(task.timer); msg.error ? task.reject(new Error(JSON.stringify(msg.error))) : task.resolve(msg.result); } else if (msg.method === 'Runtime.exceptionThrown') errors.push(msg.params.exceptionDetails.exception?.description || msg.params.exceptionDetails.text); });
const send = (method, params = {}) => new Promise((resolve, reject) => { const id = ++sequence; const timer = setTimeout(() => {pending.delete(id); reject(Error('Timed out: ' + method));}, 15000); timer.unref(); pending.set(id, {resolve, reject, timer}); socket.send(JSON.stringify({id,method,params})); });
const evaluate = async expression => { const result = await send('Runtime.evaluate', {expression, awaitPromise: true, returnByValue: true}); if (result.exceptionDetails) throw Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text); return result.result.value; };
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const check = async (expression, label) => { assert.equal(await evaluate(`Boolean(${expression})`), true, label); checks++; };
const navigate = async path => { await send('Page.navigate', {url:origin + path}); for(let i=0;i<40;i++){ await wait(100); if(await evaluate(`location.pathname === ${JSON.stringify(path.split('?')[0])} && document.readyState === 'complete' && typeof setupCartIcon === 'function'`)) return; } throw Error('Navigation timeout: ' + path); };
const key = async (key, modifiers=0) => {await send('Input.dispatchKeyEvent', {type:'keyDown', key, code:key, windowsVirtualKeyCode:key==='Tab'?9:27, modifiers}); await send('Input.dispatchKeyEvent', {type:'keyUp', key, code:key, windowsVirtualKeyCode:key==='Tab'?9:27, modifiers});};
await send('Page.enable'); await send('Runtime.enable'); await send('Network.enable'); await send('Network.setCacheDisabled',{cacheDisabled:true});
await send('Fetch.enable', {patterns:[{urlPattern:'*'}]});
socket.addEventListener('message', ({data}) => { const event = JSON.parse(data); if(event.method !== 'Fetch.requestPaused') return; const request = event.params; const allowed = request.request.url.startsWith(origin + '/') && ['GET','HEAD'].includes(request.request.method); send(allowed ? 'Fetch.continueRequest' : 'Fetch.failRequest', allowed ? {requestId:request.requestId} : {requestId:request.requestId,errorReason:'BlockedByClient'}).catch(()=>{}); });
for(const name of ['camera','microphone']) await send('Browser.setPermission',{permission:{name},setting:'denied',origin});
await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__testPostStatus=503; window.__testPostCount=0; window.__cameraRequests=0; const testFetch=window.fetch.bind(window); window.fetch=(input,options={})=>{const method=String(options.method||input?.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){window.__testPostCount++;return Promise.resolve(new Response('{}',{status:window.__testPostStatus,headers:{'Content-Type':'application/json'}}));}return testFetch(input,options);}; if(navigator.mediaDevices)Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{window.__cameraRequests++;throw Error('Camera prohibited in regression');}});`});
try {
 await navigate('/shop.html'); await evaluate('localStorage.clear(); location.reload()'); await wait(600);
 await check(`document.querySelector('[data-product-card="rise-ring"] h3').textContent === 'The Rise Ring'`, 'Short card title');
 await check(`document.querySelector('[data-product-card="rise-ring"] .product-card__materials').textContent === '14K gold · 1 ct lab-grown diamond'`, 'Grounded card materials');
 await evaluate(`document.querySelector('[data-card-add="rise-ring"]').click();document.querySelector('[data-card-add="signature-monogram-ring"]').click();document.querySelector('.cart-icon').click()`); await wait(50);
 await check(`document.querySelector('.page-shell').inert && document.activeElement.matches('.cart-modal__panel [data-cart-close]')`, 'Bag background inert and visible close focused');
 await evaluate(`document.querySelector('[data-cart-checkout]').focus()`); await key('Tab');
 await check(`document.activeElement.matches('.cart-modal__panel [data-cart-close]')`, 'Bag forward Tab wraps');
 await key('Tab',8); await check(`document.activeElement.matches('[data-cart-checkout]')`, 'Bag reverse Tab wraps');
 await evaluate(`const quantity=document.querySelector('[data-cart-quantity="rise-ring"]');quantity.focus();quantity.value='2';quantity.dispatchEvent(new Event('change',{bubbles:true}))`);
 await check(`document.activeElement.matches('[data-cart-quantity="rise-ring"]') && document.activeElement.value==='2'`, 'Quantity update preserves focus');
 await check(`document.querySelector('[data-cart-total]').textContent.includes('5,300')`, 'Bag recalculates subtotal');
 await evaluate(`document.querySelector('[data-cart-remove="rise-ring"]').focus(); document.activeElement.click()`);
 await check(`document.activeElement.matches('[data-cart-remove="signature-monogram-ring"]')`, 'Removal moves focus to remaining item');
 await evaluate(`document.activeElement.click()`);
 await check(`document.activeElement.matches('.cart-empty a') && document.querySelector('[data-cart-footer]').hidden`, 'Empty bag preserves navigation focus');
 await key('Escape'); await check(`!document.querySelector('.page-shell').inert && document.activeElement.matches('.cart-icon')`, 'Bag close restores background and trigger');
 await evaluate(`document.querySelector('.cart-icon').click();document.querySelector('.cart-modal__panel [data-cart-close]').click();document.querySelector('.cart-icon').click()`); await wait(250);
 await check(`!document.querySelector('[data-cart-modal]').hidden && document.querySelector('[data-cart-modal]').classList.contains('is-open') && document.querySelector('.page-shell').inert`, 'Close/reopen does not hide open bag');
 await key('Escape');
 await navigate('/products/the-rise-ring/');
 await check(`document.querySelector('h1').textContent.includes('1 ct Lab-Grown Diamond')`, 'Full product name preserved');
 await check(`document.querySelector('[data-product-order-note]').textContent.includes(products.find(p=>p.slug==='rise-ring').shipping) && document.querySelector('[data-product-order-note] a').getAttribute('href')==='/shipping-returns.html'`, 'Ordering expectations and policy link visible by actions');
 await check(`document.querySelector('[data-gallery-thumb]').getAttribute('aria-pressed')==='true'`, 'Initial gallery selection announced');
 await evaluate(`document.querySelectorAll('[data-gallery-thumb]')[1].click()`);
 await check(`document.querySelectorAll('[data-gallery-thumb][aria-pressed="true"]').length===1 && document.querySelectorAll('[data-gallery-thumb]')[1].getAttribute('aria-pressed')==='true'`, 'Gallery updates selected state');
 await navigate('/curated-luxuries.html');
 await check(`document.querySelector('[data-appointment-modal]').inert`, 'Closed estate dialog is inert');
 await evaluate(`document.querySelector('[data-appointment-trigger]').click()`);
 await check(`document.activeElement.matches('.modal__dialog [data-modal-close]') && !document.activeElement.closest('[inert]')`, 'Estate dialog opening focus remains interactive');
 await key('Tab',8); await check(`document.activeElement.closest('.modal__dialog') && !document.activeElement.matches('[data-modal-close]')`, 'Estate reverse Tab wraps inside panel');
 await key('Escape'); await check(`document.activeElement.matches('[data-appointment-trigger]') && document.querySelector('[data-appointment-modal]').inert`, 'Estate close restores trigger and hides interaction');
 await navigate('/contact.html');
 await evaluate(`localStorage.clear();localStorage.setItem('tj-custom-request-draft',JSON.stringify({'full-name':'Legacy Client','piece-type':'Ring','description':'An existing design draft'}));document.querySelector('#contact-name').value='Contact Client';document.querySelector('#contact-name').dispatchEvent(new Event('input',{bubbles:true}));`);
 await check(`localStorage.getItem('tj-custom-request-draft')!==null && JSON.parse(localStorage.getItem('tj-custom-request-draft:contact-inquiry'))['contact-name']==='Contact Client'`, 'Contact save preserves unrelated legacy custom draft');
 await navigate('/customs.html');
 await check(`document.querySelector('#full-name').value==='Legacy Client' && !localStorage.getItem('tj-custom-request-draft') && JSON.parse(localStorage.getItem('tj-custom-request-draft:custom-request'))['description']==='An existing design draft'`, 'Matching legacy custom draft migrates and restores');
 await check(`Boolean(localStorage.getItem('tj-custom-request-draft:contact-inquiry'))`, 'Custom migration preserves contact draft');
 await check(`document.querySelector('[data-custom-form] [data-form-status]').getAttribute('role')==='status' && document.querySelector('[data-custom-form] [data-form-status]').getAttribute('aria-live')==='polite'`, 'Inquiry status is live');
 await check(`[...document.querySelectorAll('.fieldset-title')].some(x=>x.textContent==='Preferred appointment time')`, 'Booking time phrasing is accurate');
 await check(`[...document.querySelectorAll('.faq-question')].every(button=>document.getElementById(button.getAttribute('aria-controls')) && (button.getAttribute('aria-expanded')==='true') === !document.getElementById(button.getAttribute('aria-controls')).hidden)`, 'All FAQs expose matching expansion state');
 await evaluate(`document.querySelectorAll('.faq-question')[1].click()`);
 await check(`document.querySelectorAll('.faq-question')[1].getAttribute('aria-expanded')==='true' && !document.querySelectorAll('.faq-answer')[1].hidden`, 'FAQ opens accessibly');
 await evaluate(`document.querySelector('#email-address').value='test@example.invalid';document.querySelector('#piece-type').value='Ring';document.querySelector('[data-custom-form]').requestSubmit()`); await wait(200);
 await check(`window.__testPostCount===1 && document.querySelector('#full-name').value==='Legacy Client' && document.querySelector('[data-custom-form] [data-form-status] a').href==='mailto:info@torontojewelscuration.com'`, 'Mock failure preserves form and offers usable recovery');
 await evaluate(`window.__testPostStatus=200;document.querySelector('[data-custom-form]').requestSubmit()`); await wait(500);
 await check(`!localStorage.getItem('tj-custom-request-draft:custom-request') && Boolean(localStorage.getItem('tj-custom-request-draft:contact-inquiry')) && document.querySelector('[data-form-draft-indicator]').hidden`, 'Mock success clears only submitted draft without re-saving reset');
 await navigate('/contact.html');
 await check(`document.querySelector('#contact-name').value==='Contact Client'`, 'Independent contact draft restores after custom submission');
 await evaluate(`localStorage.removeItem('tj-custom-request-draft:contact-inquiry');localStorage.setItem('tj-custom-request-draft',JSON.stringify({'unknown-field':'Keep me'}));location.reload()`); await wait(500);
 await check(`JSON.parse(localStorage.getItem('tj-custom-request-draft'))['unknown-field']==='Keep me' && !localStorage.getItem('tj-custom-request-draft:contact-inquiry')`, 'Unidentifiable legacy draft is preserved without migration');
 await navigate('/shop.html');
 await evaluate(`document.querySelector('[data-personal-edit-open]').focus();document.querySelector('[data-personal-edit-open]').click()`);
 await check(`document.querySelector('.personal-edit-dialog').open && document.querySelectorAll('.personal-edit-result').length > 0`, 'Finder opens with results');
 await evaluate(`const type=document.querySelector('[data-personal-type]');type.value='earrings';type.dispatchEvent(new Event('change'));const budget=document.querySelector('[data-personal-budget]');budget.value='1500';budget.dispatchEvent(new Event('change'))`);
 await check(`document.querySelectorAll('.personal-edit-result').length===0 && document.querySelector('.personal-edit-status').textContent.includes('No published-price pieces match')`, 'Finder respects category and CAD budget empty state');
 await key('Escape');
 await check(`!document.querySelector('.personal-edit-dialog').open && document.activeElement.matches('[data-personal-edit-open]')`, 'Finder restores trigger focus');
 await navigate('/customs.html');
 await evaluate(`const note=document.querySelector('#description');note.value='Keep my existing note';note.dispatchEvent(new Event('input',{bubbles:true}));const metal=document.querySelector('#metal-preference');metal.value='Rose gold';metal.dispatchEvent(new Event('input',{bubbles:true}))`);
 await navigate('/products/the-rise-ring/');
 await check(`document.querySelector('[data-buy-now]').textContent==='Request order confirmation'`, 'Product action requests confirmation');
 await evaluate(`document.querySelector('[data-buy-now]').click()`);
 for(let i=0;i<40;i++){await wait(100);if(await evaluate(`location.pathname==='/customs.html' && !!document.querySelector('#description')?.value.includes('[Order Enquiry]')`)) break;}
 await check(`document.querySelector('#description').value.includes('1 × The Rise Ring') && document.querySelector('#description').value.startsWith('Keep my existing note') && document.querySelector('#metal-preference').value==='Rose gold'`, 'Direct enquiry preserves draft and selected piece');
 await navigate('/products/the-rise-ring/');
 await evaluate(`document.querySelector('[data-add-to-cart]').click();document.querySelector('.cart-icon').click();const quantity=document.querySelector('[data-cart-quantity="rise-ring"]');quantity.value='2';quantity.dispatchEvent(new Event('change',{bubbles:true}))`);
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await wait(300);
 await check(`document.querySelector('.cart-modal__panel').getBoundingClientRect().right <= innerWidth + 1 && document.querySelector('[data-cart-checkout]').textContent==='Request order confirmation'`, 'Mobile bag fits viewport and offers enquiry');
 await evaluate(`document.querySelector('[data-cart-checkout]').click()`);
 for(let i=0;i<40;i++){await wait(100);if(await evaluate(`location.pathname==='/customs.html' && !!document.querySelector('#description')?.value.includes('2 × The Rise Ring')`)) break;}
 await check(`document.querySelector('#description').value.includes('2 × The Rise Ring') && document.querySelector('#description').value.split('[Order Enquiry]').length===2 && document.querySelector('#description').value.startsWith('Keep my existing note') && readCart().find(item=>item.slug==='rise-ring').quantity===2`, 'Bag handoff preserves quantities, draft, and bag without duplicate blocks');
 await check(`document.documentElement.scrollWidth<=innerWidth && window.__testPostCount===0`, 'Mobile enquiry has no overflow and handoff does not submit');
 await send('Page.reload'); await wait(600);
 await check(`document.querySelector('#description').value.includes('2 × The Rise Ring') && document.querySelector('#description').value.split('[Order Enquiry]').length===2 && document.querySelector('#metal-preference').value==='Rose gold'`, 'Reload preserves enquiry and unrelated fields');
 await send('Emulation.clearDeviceMetricsOverride');
 await check(`window.__cameraRequests===0`, 'No camera used');
 assert.deepEqual(errors, [], 'No runtime exceptions'); checks++;
 console.log(JSON.stringify({passed:checks, runtimeErrors:errors, submissions:'Mock responses only; no external POST requests',browser:'Isolated headless profile'}));
} finally { socket.close(); }
