"""Build responsive WebP photographs; never overwrite source photography.

Requires Pillow (python -m pip install Pillow). Run from any directory; --force
rebuilds existing variants. Add new catalogue photos to main.js first.
Full-screen gallery links keep their original sources.
"""
import hashlib
import json
import re
import sys
from io import BytesIO
from pathlib import Path
from PIL import Image, ImageCms, ImageOps

ROOT = Path(__file__).resolve().parent.parent
MAIN = ROOT / 'assets/js/main.js'
OUT = ROOT / 'assets/images/responsive'
OUT.mkdir(exist_ok=True)
main = MAIN.read_text()
previous_match = re.search(r'const responsivePhotos = (\{[^\n]+\});', main)
previous = json.loads(previous_match[1]) if previous_match else {}
previous_files = {OUT / f'{stem}-{width}.webp' for stem, widths in previous.values() for width in widths}
main = re.sub(r'// BEGIN RESPONSIVE PHOTOS.*?// END RESPONSIVE PHOTOS\n', '', main, flags=re.S)
pages = sorted(ROOT.glob('*.html')) + sorted(ROOT.glob('*/index.html')) + sorted(ROOT.glob('*/*/index.html'))
sources = set(re.findall(r'["\'](/assets/images/[^"\']+\.(?:jpeg|jpg|png))["\']', main))
for page in pages:
    sources.update('/' + src.lstrip('/') for src in re.findall(r'<img\b[^>]*\bsrc="(/?assets/images/[^"?]+\.(?:jpg|jpeg|png))"', page.read_text()))
sources = sorted(src for src in sources if '/responsive/' not in src)
manifest = {}
for src in sources:
    path = ROOT / src.lstrip('/')
    if not path.exists():
        continue
    with Image.open(path) as original:
        photo = ImageOps.exif_transpose(original)
        profile = photo.info.get('icc_profile')
        if profile:
            photo = ImageCms.profileToProfile(photo, ImageCms.ImageCmsProfile(BytesIO(profile)),
                                            ImageCms.createProfile('sRGB'), outputMode='RGBA' if 'A' in photo.getbands() else 'RGB')
        else:
            photo = photo.convert('RGBA' if photo.mode == 'RGBA' else 'RGB')
    width, height = photo.size
    if width < 300:
        continue
    # A replacement photo or encoder recipe gets a new URL despite CDN caching.
    stem = path.stem + '-' + hashlib.sha256(src.encode() + path.read_bytes() + b'webp-q86-v1').hexdigest()[:8]
    widths = sorted(set(min(width, target) for target in [160, 320, 480, 780, 1280]))
    for size in widths:
        dest = OUT / f'{stem}-{size}.webp'
        if not dest.exists() or '--force' in sys.argv:
            photo.resize((size, round(height * size / width)), Image.Resampling.LANCZOS).save(
                dest, 'WEBP', quality=86, method=6)
    manifest[src] = [stem, widths]

block = '// BEGIN RESPONSIVE PHOTOS — generated by scripts/optimize_storefront_images.py\n'
block += 'const responsivePhotos = ' + json.dumps(manifest, separators=(',', ':')) + ';\n'
block += '// END RESPONSIVE PHOTOS\n'
MAIN.write_text(block + main)

def candidates(src):
    stem, widths = manifest[src]
    return ', '.join(f'/assets/images/responsive/{stem}-{w}.webp {w}w' for w in widths)

for page in pages:
    text = page.read_text()
    def image(match):
        tag = match[0]
        src_match = re.search(r'\bsrc="([^"]+)"', tag)
        if not src_match:
            return tag
        src = '/' + src_match[1].lstrip('/')
        if src not in manifest:
            return tag
        is_thumb = 'width="80"' in tag
        sizes_match = re.search(r'\bsizes="([^"]+)"', tag)
        sizes = sizes_match[1] if sizes_match else ('80px' if is_thumb else '(max-width: 700px) 100vw, 50vw')
        # Small static collection fallbacks must not fetch full-width pictures.
        if ('product-card' in text[max(0, match.start()-180):match.start()] or 'data-product-card' in tag):
            sizes = '(max-width: 700px) 44vw, 23vw'
        tag = re.sub(r'\s+(?:srcset|sizes)="[^"]*"', '', tag)
        if 'decoding=' not in tag:
            tag = tag[:-1] + ' decoding="async">'
        return tag[:-1] + f' srcset="{candidates(src)}" sizes="{sizes}">'
    text = re.sub(r'<img\b[^>]+>', image, text)
    # Keep the high-priority preload identical to the hero's source selection.
    def preload(match):
        tag = match[0]
        href = re.search(r'\bhref="([^"]+)"', tag)
        src = '/' + href[1].lstrip('/') if href else ''
        if src not in manifest:
            return tag
        tag = re.sub(r'\s+imagesrcset="[^"]*"', '', tag)
        return tag[:-1] + f' imagesrcset="{candidates(src)}">'
    text = re.sub(r'<link\b[^>]*\bas="image"[^>]*>', preload, text)
    page.write_text(text)
current_files = {OUT / f'{stem}-{width}.webp' for stem, widths in manifest.values() for width in widths}
for stale in previous_files - current_files:
    stale.unlink(missing_ok=True)
print(f'Built responsive variants for {len(manifest)} photographs; originals preserved.')
