"""Build responsive WebP photographs; never overwrite source photography.

Requires Pillow (python -m pip install Pillow). Run from any directory; --force
rebuilds existing variants. Add new catalogue photos to main.js first.
Full-screen gallery links keep their original sources.
"""
import hashlib
import json
import re
import sys
from io import BytesIO
from pathlib import Path
from PIL import Image, ImageCms, ImageOps

ROOT = Path(__file__).resolve().parent.parent
MAIN = ROOT / 'assets/js/main.js'
OUT = ROOT / 'assets/images/responsive'
OUT.mkdir(exist_ok=True)
main = MAIN.read_text()
previous_match = re.search(r'const responsivePhotos = (\{[^\n]+\});', main)
previous = json.loads(previous_match[1]) if previous_match else {}
previous_files = {OUT / f'{stem}-{width}.webp' for stem, widths in previous.values() for width in widths}
main = re.sub(r'// BEGIN RESPONSIVE PHOTOS.*?// END RESPONSIVE PHOTOS\n', '', main, flags=re.S)
pages = sorted(ROOT.glob('*.html')) + sorted(ROOT.glob('*/index.html')) + sorted(ROOT.glob('*/*/index.html'))
sources = set(re.findall(r'["\'](/assets/images/[^"\']+\.(?:jpeg|jpg|png|webp))["\']', main))
for page in pages:
    for tag in re.findall(r'<img\b[^>]+>', page.read_text()):
        src = re.search(r'\bsrc="(/?assets/images/[^"?]+\.(?:jpg|jpeg|png|webp))"', tag)
        if src and 'data-responsive-manual' not in tag:
            sources.add('/' + src[1].lstrip('/'))
    sources.update('/' + src.lstrip('/') for src in re.findall(r'(?:poster|data-poster-source)="(/?assets/images/[^"?]+\.(?:jpg|jpeg|png|webp))"', page.read_text()))
sources = sorted(src for src in sources if '/responsive/' not in src)
manifest = {}
dimensions = {}
for src in sources:
    path = ROOT / src.lstrip('/')
    if not path.exists():
        continue
    # Encode studio variants directly from the retained PNG, avoiding a second
    # lossy encode of the WebP fallback. Never synthesize extra source detail.
    master = path.parent / 'sources' / (path.stem + '.png') if '/studio/' in src else path
    if not master.exists():
        master = path
    with Image.open(master) as original:
        photo = ImageOps.exif_transpose(original)
        profile = photo.info.get('icc_profile')
        if profile:
            photo = ImageCms.profileToProfile(photo, ImageCms.ImageCmsProfile(BytesIO(profile)),
                                            ImageCms.createProfile('sRGB'), outputMode='RGBA' if 'A' in photo.getbands() else 'RGB')
        else:
            photo = photo.convert('RGBA' if photo.mode == 'RGBA' else 'RGB')
    width, height = photo.size
    dimensions[src] = (width, height)
    if width < 300:
        continue
    # A replacement photo or encoder recipe gets a new URL despite CDN caching.
    stem = path.stem + '-' + hashlib.sha256(src.encode() + master.read_bytes() + b'webp-q86-v1').hexdigest()[:8]
    widths = sorted(set(min(width, target) for target in [160, 320, 480, 780, 1280]))
    for size in widths:
        dest = OUT / f'{stem}-{size}.webp'
        if not dest.exists() or '--force' in sys.argv:
            photo.resize((size, round(height * size / width)), Image.Resampling.LANCZOS).save(
                dest, 'WEBP', quality=86, method=6)
    manifest[src] = [stem, widths]

block = '// BEGIN RESPONSIVE PHOTOS — generated by scripts/optimize_storefront_images.py\n'
block += 'const responsivePhotos = ' + json.dumps(manifest, separators=(',', ':')) + ';\n'
block += '// END RESPONSIVE PHOTOS\n'
MAIN.write_text(block + main)

def candidates(src):
    stem, widths = manifest[src]
    return ', '.join(f'/assets/images/responsive/{stem}-{w}.webp {w}w' for w in widths)

for page in pages:
    text = page.read_text()
    def image(match):
        tag = match[0]
        if 'data-responsive-manual' in tag:
            return tag
        src_match = re.search(r'\bsrc="([^"]+)"', tag)
        if not src_match:
            return tag
        src = '/' + src_match[1].lstrip('/')
        if src not in manifest:
            return tag
        is_thumb = 'width="80"' in tag
        sizes_match = re.search(r'\bsizes="([^"]+)"', tag)
        sizes = sizes_match[1] if sizes_match else ('80px' if is_thumb else '(max-width: 700px) 100vw, 50vw')
        # Small static collection fallbacks must not fetch full-width pictures.
        if ('product-card' in text[max(0, match.start()-180):match.start()] or 'data-product-card' in tag):
            sizes = '(max-width: 700px) 44vw, 23vw'
        tag = re.sub(r'\s+(?:srcset|sizes)="[^"]*"', '', tag)
        if 'decoding=' not in tag:
            tag = tag[:-1] + ' decoding="async">'
        if 'width=' not in tag and 'height=' not in tag:
            width, height = dimensions[src]
            tag = tag[:-1] + f' width="{width}" height="{height}">'
        return tag[:-1] + f' srcset="{candidates(src)}" sizes="{sizes}">'
    text = re.sub(r'<img\b[^>]+>', image, text)
    def poster(match):
        tag = match[0]
        original = re.search(r'\bdata-poster-source="([^"]+)"', tag)
        current = re.search(r'\bposter="([^"]+)"', tag)
        if not current:
            return tag
        src = '/' + (original or current)[1].lstrip('/')
        if src not in manifest:
            return tag
        stem, widths = manifest[src]
        size = max(w for w in widths if w <= 780)
        tag = tag.replace(current[0], f'poster="/assets/images/responsive/{stem}-{size}.webp"')
        if not original:
            tag = tag[:-1] + f' data-poster-source="{src}">'
        return tag
    text = re.sub(r'<video\b[^>]+>', poster, text)
    # Keep the high-priority preload identical to the hero's source selection.
    def preload(match):
        tag = match[0]
        href = re.search(r'\bhref="([^"]+)"', tag)
        src = '/' + href[1].lstrip('/') if href else ''
        if src not in manifest:
            return tag
        tag = re.sub(r'\s+imagesrcset="[^"]*"', '', tag)
        return tag[:-1] + f' imagesrcset="{candidates(src)}">'
    text = re.sub(r'<link\b[^>]*\bas="image"[^>]*>', preload, text)
    page.write_text(text)
current_files = {OUT / f'{stem}-{width}.webp' for stem, widths in manifest.values() for width in widths}
for stale in previous_files - current_files:
    stale.unlink(missing_ok=True)
print(f'Built responsive variants for {len(manifest)} photographs; originals preserved.')
